<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <h3>Would you love to sell your products here at Bazaar Corner?</h3>
            <p>Join our community of known merchants and resellers.</p>
        </div>
        <div class="col-lg-4 col-md-4" style="border-left: 1px solid silver">
            <h3>I'm a Buyer</h3>
            <p>I would like to join the Bazaar Corner community</p>
            <div class="container-fluid" style="box-shadow: 0px 0px 1px silver; padding: 10px">
                <form method="post" action="<?=$this->url('member/registration')?>">
                    <div class="row-fluid">
                        <h5><strong>Register As:</strong></h5>
                        <em class="text-muted" style="font-size: 11px;">* All input fields are required</em>                        
                    </div>
                    <div class="divider"><hr><br></div>
                    <div class="form-group"><input class="form-control" type="text" placeholder="username" name="username"></div>
                    <div class="form-group"><input class="form-control" type="password" placeholder="password" name="password"></div>
                    <div class="form-group"><input class="form-control" type="password" placeholder="confirmation: re-type password" name="password_confirmation"></div>
                    <div class="form-group"><input class="form-control" type="email" placeholder="email address" name="email"></div>
                    <em class="text-muted" style="font-size: 11px;">Kindly ensure your email is up-to-date and accessible to receive updates and promotions.</em>
                    <br><br>
                    <div class="row">
                        <div class="col-md-8">
                            <span class="pull-left" style="font-weight: bold;">
                                Agree with our <a href="<?=$this->url('terms')?>#buyer" target="_blank">Terms</a>?
                            </span>
                            <br>
                            <div class="form-group">
                                <input class="checkbox checkbox-inline" type="checkbox" value="1" name="agreed">
                                <span>Yes, I agree.</span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <input class="btn btn-danger pull-right" type="submit" value="Join Bazaar!">
                            </div>
                        </div>                        
                    </div>
                    <em class="text-muted" style="font-size: 11px;">** We value your information. Read more about our <a href="<?=$this->url('policy')?>" class="text-capitalize" target="_blank">privacy policy</a>.</em>
                </form>
            </div>
            <br>
            <h4>Have existing account?</h4>
            <a href="<?=$this->url('member/login')?>">Click here to sign in</a>
            <div class="clearfix"></div>
            <br>
            <div class="divider"><hr></div>
            <div class="row-fluid">
                <h3>OR: </h3>
                <ul class="list-inline text-center">
                    <li>
                        <a class="btn btn-primary"
                           href="#"
                           role="button">
                            <i class="fa fa-facebook fa-lg"></i>
                            Login with Facebook
                        </a>
                    </li>
                    <li>
                        <a class="btn btn-info"
                           href="#"
                           role="button">
                            <i class="fa fa-twitter fa-lg"></i>
                            Login with Twitter
                        </a>
                    </li>
                </ul>
                <em class="text-muted" style="font-size: 11px;">** We're not going to post or share anything without your permission.</em>
            </div>
        </div>
    </div>
</div>