<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <h3>Would you love to sell your products here at Bazaar Corner?</h3>
            <p>Join our community of known merchants and resellers.</p>
        </div>
        <div class="col-lg-4 col-md-4" style="border-left: 1px solid silver">
            <h3>I'm a Buyer 
                <small class="text-warning">
                    (<strong>FREE account</strong>)
                </small>
            </h3>
            <p>I would like to join the Bazaar Corner community</p>
            <?php echo $this->partial('template/partial/registration-form'); ?> 
            <h4>Have existing account?</h4>
            <a href="<?=$this->url('member/login')?>">Click here to sign in</a>
            <div class="clearfix"></div>
            <?php echo $this->partial('template/partial/socials', []); ?>            
        </div>
    </div>    
</div>