<div class="col-lg-3">
    <ul>
        <li>
            <h3>My Account</h3>
            <ul>
                
            </ul>
        </li>
        <!-- if merchant -->
        <li><h3>My Catalog</h3></li>
    </ul>
<!--    <ul>
        <h3>Account</h3>
        <li><a href="<?=$this->url('member/account')?>">Settings</a></li>
        <li><a href="<?=$this->url('member/billing')?>">Billing</a></li>
        <li><a href="<?=$this->url('member/payments')?>">Payments</a></li>
        <li><a href="<?=$this->url('member/orders')?>">Orders</a></li>        
    </ul>-->
</div>
<div class="col-lg-7">
    
</div>
<div class="col-lg-2">
    <h5>Advertisements Here</h5>
</div>