<div class="content-holder">
    <div class="content-header">
        <div class="container-fluid text-capitalize">
            <div class="pull-left">
                Account Settings
            </div>
            <div class="pull-right">                
                <a href="<?=$this->basePath($this->member->username)?>" 
                   role="button" 
                   class="btn btn-danger btn-xs">
                    View Profile
                    <!--<i class="fa fa-plus"></i>-->
                </a>
            </div>
        </div>
    </div>

    <div class="content-body">
        <div class="container-fluid">
            This is my contents
        </div>
    </div>
</div>