<br>
<div class="divider"><hr></div>
<div class="row-fluid">
    <h3>OR: </h3>
    <ul class="list-inline text-center">
        <li>
            <a class="btn btn-primary"
               href="#"
               role="button">
                <i class="fa fa-facebook fa-lg"></i>
                Log in with Facebook
            </a>
        </li>
        <li>
            <a class="btn btn-info"
               href="#"
               role="button">
                <i class="fa fa-twitter fa-lg"></i>
                Log in with Twitter
            </a>
        </li>
    </ul>
    <em class="text-muted" style="font-size: 11px;">** We're not going to post or share anything without your permission.</em>
</div>