<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-4">
            <h3>I already have an account</h3>            
            <p>I would like to sign in with my account.</p>
            <div class="container-fluid" style="box-shadow: 0px 0px 1px silver; padding: 10px">    
                <form method="POST" action="<?=$this->url('member/login')?>">                    
                    <div class="row-fluid">
                        <p><strong>Sign As:</strong></p>
                    </div>
                    <div class="divider"><hr><br></div>
                    <div class="form-group"><input class="form-control" type="text" placeholder="username" name="username"></div>
                    <div class="form-group"><input class="form-control" type="password" placeholder="password" name="password"></div>
                    <div class="row">
                        <div class="col-md-8">
                            <span class="pull-left text-capitalize" style="font-weight: bold;">Forgot your password? </span>
                            <br>
                            <a href="#">Click here to reset your password</a> 
                            
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <input class="btn btn-danger pull-right" type="submit" value="Sign In">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <br>
            <h4>Don't have an account?</h4>
            <a href="<?= $this->url('member/registration')?>">
                Click here to register (it's FREE)
            </a>
            <div class="clearfix"></div>
            <br>
            <div class="divider"><hr></div>
            <div class="row-fluid">
                <h3>OR: </h3>
                <ul class="list-inline text-center">
                    <li>
                        <a class="btn btn-primary"
                           href="#"
                           role="button">
                            <i class="fa fa-facebook fa-lg"></i>
                            Log in with Facebook
                        </a>
                    </li>
                    <li>
                        <a class="btn btn-info"
                           href="#"
                           role="button">
                            <i class="fa fa-twitter fa-lg"></i>
                            Log in with Twitter
                        </a>
                    </li>
                </ul>
                <em class="text-muted" style="font-size: 11px;">** We're not going to post or share anything without your permission.</em>
            </div>
        </div>
        <div class="col-lg-8 col-md-8" style="border-left: 1px solid silver">
            <div id="banner" class="carousel carousel-shadow slide" data-ride="carousel">
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <a href="#"><img src="<?= $this->basePath('assets/img/site/banners/fashion.jpg') ?>" alt="Fashion"></a>
                    </div>
                    <div class="item">
                        <a href="#"><img src="<?= $this->basePath('assets/img/site/banners/homewares.jpg') ?>" alt="Home Wares"></a>
                    </div>
                    <div class="item">
                        <a href="#"><img src="<?= $this->basePath('assets/img/site/banners/DIY.jpg')?>" alt="DIY"></a>
                    </div>
                    <div class="item">
                        <a href="#"><img src="<?= $this->basePath('assets/img/site/banners/gadgets.jpg')?>" alt="Gadgets"></a>
                    </div>
                </div>
            </div>
            <div class="divider"><hr></div>
            <div class="row-fluid">
                <h4>Featured Brands</h4>
                <ul class="list-inline">
                    <li>Hugo Boss</li>
                    <li>Chanel</li>
                    <li>Prada</li>
                    <li>Paul Smith</li>
                </ul>
            </div>            
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <div class="pull-left">
                        <img class="bazaarlogorevo" 
                            src="<?= $this->basePath('assets/img/site/logo-revo.png');?>">
                        <h2 id="fittext2">Revolutionize the way you shop!</h2>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="pull-right">
                        <img class="revopic" 
                            src="<?= $this->basePath('assets/img/site/stockphoto02.jpg');?>">
                    </div>
                </div>
                
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>